### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by BangBangBoss** [tobias17/sd-exodia#2]
D:\sd-exodia-main>python render.py srun
['sidle', 'srun00', 'srun01', 'srun02', 'srun03', 'srun04', 'srun05', 'srun06', 'srun07', 'srun08', 'srun09', 'srun10', 'srun11', 'srun12', 'srun13', 'srun14', 'srun15', 'srun16', 'srun17', 'srun18', 'srun19']
  0%|                                                                                           | 0/21 [00:00<?, ?it/s]{'detail': 'Not Found'}
  0%|                                                                                           | 0/21 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\sd-exodia-main\render.py", line 506, in <module>
    run_folder(sys.argv[1])
  File "D:\sd-exodia-main\render.py", line 499, in run_folder
    run_through_sd(anim_folder, anim_name, paths, full_payload, face_payload, run, f"{render_root}/iter000")
  File "D:\sd-exodia-main\render.py", line 386, in run_through_sd
    enc_imgs = call_sd(payload, enc_img, enc_face if run_face else enc_mask, enc_pose)
  File "D:\sd-exodia-main\render.py", line 136, in call_sd
    raise RuntimeError("Could not find key 'images' in response from server.")
RuntimeError: Could not find key 'images' in response from server.

**Comment by BangBangBoss** [comment]
I apologize for my question. It was my first time using Python to call the Stable Diffusion API. The error seemed to indicate that I was connected to the local server, but I didn't receive a response. After investigating in that direction, I added "--api" to the parameters when running the batch file, and it worked successfully.

However, during the runtime, I kept encountering the following error in the Stable Diffusion console. I'm noting it here for future reference, and I will investigate the cause further:

*** Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
File "D:\stable-diffusion-webui\modules\scripts.py", line 474, in process
script.process(p, *script_args)
File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 992, in process
model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 674, in load_control_model
model_net = self.build_control_model(p, unet, model, lowvram)
File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in build_control_model
raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None

Finally, I would like to express my sincere gratitude to tobias17 for their valuable insights. They have exceptional technical skills, and their efficiency has improved significantly.

**Comment by tobias17** [comment]
In the render file, there is a controlnet model name parameter (https://github.com/tobias17/sd-exodia/blob/main/render.py#L36C71-L36C71)

1. If you do not have an openpose controlnet model you will need to download that first
2. You will need to copy the name (including the hash) into the parameter (in render.py linked above)

**Comment by BangBangBoss** [comment]
Thank you very much. Indeed, I modified the model name and hash in the render.py file, and the error is no longer occurring. 
However, a new error has emerged, and it appears that the mask_blur parameter is not being passed when calling sd. I don't have much programming background, and I'm unsure how to modify it to resolve the issue.

*** Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1080, in process
        if p.mask_blur > 0:
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'mask_blur'

**Comment by BangBangBoss** [comment]
Resolved! The issue was caused by outdated controlnet extensions. After updating controlnet to the latest version (v1.1.233) in the webui, the error is no longer present. I want to express my sincere gratitude to tobias17 for your excellence and generous spirit in sharing your work. It's truly amazing and very useful!
